// Create Today Date(ex: 2020-07-01)
function getTodayDate() {
  const fullDate = new Date();
  const yyyy = fullDate.getFullYear();
  const MM = (fullDate.getMonth() + 1) >= 10 ? (fullDate.getMonth() + 1) : (`0${fullDate.getMonth() + 1}`);
  const dd = fullDate.getDate() < 10 ? (`0${fullDate.getDate()}`) : fullDate.getDate();
  const today = `${yyyy}-${MM}-${dd}`;
  return today;
}

const users = [
  {
    provider: 'native',
    email: 'test1@gmail.com',
    password: 'test1password',
    name: 'test1',
    picture: null,
    access_token: 'test1accesstoken',
    access_expired: (60 * 60), // 1hr by second
    login_at: new Date('2020-01-01'),
  },
  {
    provider: 'facebook',
    email: 'test2@gmail.com',
    password: null,
    name: 'test2',
    picture: 'https://graph.facebook.com/1/picture?type=large',
    access_token: 'test2accesstoken',
    access_expired: (60 * 60), // 1hr by second
    login_at: new Date('2020-01-01'),
  },
  {
    provider: 'native',
    email: 'test3@gmail.com',
    password: 'test3passwod',
    name: 'test3',
    picture: null,
    access_token: 'test3accesstoken',
    access_expired: 0,
    login_at: new Date('2020-01-01'),
  },
];

const products = [
  {
    category: 'men',
    chinese_list: '上衣',
    type: 'tp1',
    chinese_type: '襯衫',
    name: 'product1',
    number: 1111,
    about: 'Product 1',
    texture: 'tt1',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/1111/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/1111/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/1111/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'men',
    chinese_list: '下身',
    type: 'tp2',
    chinese_type: '褲子',
    name: 'product2',
    number: 2222,
    about: 'Product 2',
    texture: 'tt2',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/2222/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/2222/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/2222/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'men',
    chinese_list: '外套',
    type: 'tp3',
    chinese_type: '風衣',
    name: 'product3',
    number: 3333,
    about: 'Product 3',
    texture: 'tt3',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/3333/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/3333/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/3333/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'men',
    chinese_list: '上衣',
    type: 'tp4',
    chinese_type: '襯衫',
    name: 'product4',
    number: 4444,
    about: 'Product 4',
    texture: 'tt4',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/4444/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/4444/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/4444/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'men',
    chinese_list: '下身',
    type: 'tp5',
    chinese_type: '褲子',
    name: 'product5',
    number: 5555,
    about: 'Product 5',
    texture: 'tt5',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/5555/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/5555/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/5555/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'men',
    chinese_list: '外套',
    type: 'tp6',
    chinese_type: '風衣',
    name: 'test searchkey product6',
    number: 6666,
    about: 'Product 6',
    texture: 'tt6',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/6666/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/6666/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/6666/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'men',
    chinese_list: '上衣',
    type: 'tp7',
    chinese_type: '襯衫',
    name: 'test searchkey product7',
    number: 7777,
    about: 'Product 7',
    texture: 'tt7',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/7777/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/7777/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/7777/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'men',
    chinese_list: '下身',
    type: 'tp8',
    chinese_type: '褲子',
    name: 'test searchkey product8',
    number: 8888,
    about: 'Product 8',
    texture: 'tt8',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/8888/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/8888/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/8888/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'men',
    chinese_list: '外套',
    type: 'tp9',
    chinese_type: '風衣',
    name: 'test searchkey product9',
    number: 9999,
    about: 'Product 9',
    texture: 'tt9',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/9999/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/9999/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/9999/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'men',
    chinese_list: '上衣',
    type: 'tp10',
    chinese_type: '襯衫',
    name: 'test searchkey product10',
    number: 10101010,
    about: 'Product 10',
    texture: 'tt10',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/10101010/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/10101010/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/10101010/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'men',
    chinese_list: '下身',
    type: 'tp11',
    chinese_type: '褲子',
    name: 'product11',
    number: 11111111,
    about: 'Product 11',
    texture: 'tt11',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/11111111/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/11111111/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/11111111/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'men',
    chinese_list: '外套',
    type: 'tp12',
    chinese_type: '風衣',
    name: 'product12',
    number: 12121212,
    about: 'Product 12',
    texture: 'tt12',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/12121212/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/12121212/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/12121212/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'women',
    chinese_list: '上衣',
    type: 'tp13',
    chinese_type: '襯衫',
    name: 'product13',
    number: 13131313,
    about: 'Product 13',
    texture: 'tt13',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/13131313/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/13131313/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/13131313/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'women',
    chinese_list: '下身',
    type: 'tp14',
    chinese_type: '褲子',
    name: 'product14',
    number: 14141414,
    about: 'Product 14',
    texture: 'tt14',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/14141414/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/14141414/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/14141414/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'kids',
    chinese_list: '上衣',
    type: 'tp15',
    chinese_type: '襯衫',
    name: 'product15',
    number: 15151515,
    about: 'Product 15',
    texture: 'tt15',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/15151515/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/15151515/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/15151515/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'kids',
    chinese_list: '下身',
    type: 'tp16',
    chinese_type: '褲子',
    name: 'product16',
    number: 16161616,
    about: 'Product 16',
    texture: 'tt16',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/16161616/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/16161616/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/16161616/item/1.jpg"]',
    update_at: getTodayDate(),
  },
  {
    category: 'kids',
    chinese_list: '外套',
    type: 'tp17',
    chinese_type: '風衣',
    name: 'product17',
    number: 17171717,
    about: 'Product 17',
    texture: 'tt17',
    main_image: 'https://im.uniqlo.com/images/tw/gu/pc/goods/17171717/item/main.jpg',
    images: '["https://im.uniqlo.com/images/tw/gu/pc/goods/17171717/item/0.jpg","https://im.uniqlo.com/images/tw/gu/pc/goods/17171717/item/1.jpg"]',
    update_at: getTodayDate(),
  },
];

const date_prices = [
  {
    date: '2020-08-01',
    price: 1000,
    product_id: 1,
  },
  {
    date: '2020-08-02',
    price: 900,
    product_id: 1,
  },
  {
    date: '2020-08-03',
    price: 900,
    product_id: 1,
  },
  {
    date: '2020-08-01',
    price: 500,
    product_id: 2,
  },
  {
    date: '2020-08-02',
    price: 400,
    product_id: 2,
  },
];

module.exports = {
  users,
  products,
  date_prices,
};
